apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloader-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downloader
  template:
    metadata:
      labels:
        app: downloader
    spec:
      containers:
      - image: mu2729/streaming-downloader
        name: downloader
        env:
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_SERVER_HTTP_PORT
          value: "8080"
        - name: KUMULUZEE_SERVER_BASE-URL
          value: http://159.122.186.127:34497
        - name: KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL
          value: http://etcd:2379/health
        - name: SERVICE_OS
          value: linux
        - name: SERVICE_FILES_PATH
          value: /files/
        ports:
        - containerPort: 8080
          protocol: TCP
          name: downloader-port
        livenessProbe:
          httpGet:
            path: /health
            port: downloader-port
          initialDelaySeconds: 30
          periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: downloader
spec:
  type: NodePort
  selector:
      app: downloader
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8080